//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Layer.DAO.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Parametros {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Parametros() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Layer.DAO.Resources.Parametros", typeof(Parametros).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 1.
        /// </summary>
        public static string IdAdmin {
            get {
                return ResourceManager.GetString("IdAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 109.
        /// </summary>
        public static string IdEstadoTicket {
            get {
                return ResourceManager.GetString("IdEstadoTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 1851.
        /// </summary>
        public static string IdEstadoTicketAsignado {
            get {
                return ResourceManager.GetString("IdEstadoTicketAsignado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 1850.
        /// </summary>
        public static string IdEstadoTicketCreado {
            get {
                return ResourceManager.GetString("IdEstadoTicketCreado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 146.
        /// </summary>
        public static string IdTipoBusqueda {
            get {
                return ResourceManager.GetString("IdTipoBusqueda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 1.
        /// </summary>
        public static string IdTipoPerfil {
            get {
                return ResourceManager.GetString("IdTipoPerfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 108.
        /// </summary>
        public static string IdTipoSolicitud {
            get {
                return ResourceManager.GetString("IdTipoSolicitud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 3.
        /// </summary>
        public static string NumeroIntentos {
            get {
                return ResourceManager.GetString("NumeroIntentos", resourceCulture);
            }
        }
    }
}
